### ISSUE TITLE
Notify suggestion authors when their suggestions get accepted/rejected

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2094]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1398862](https://bugzilla.mozilla.org/show_bug.cgi?id=1398862)
Bug Reporter: @mathjazz
CC:   @flodolo

We should probably do that periodically and aggregate notifications.

**Comment by eemeli** [comment]
Starting work on this. As an initial plan, the notification text would be something like:
> In Foo, # of your suggestions were accepted and # rejected
> In Bar, one of your suggestions was rejected

The numbers there would update as a side effect of the accept/reject actions. On each such action:
1. If an accepted-strings notification exists and it’s unread, update it.
2. Else, if an accepted-strings notification exists and it’s less than 24 hours old, update it and set it as unread.
3. Else, create a new accepted-strings notification.

As we should update the notification's timestamp when updating, we'll probably need to add something like an `orig_timestamp` field to the notification data in order to handle the second condition. We'll definitely need the `accepted` and `rejected` numbers there so that they don't need to be parsed from the notification text.

**Comment by flodolo** [comment]
I think we should simplify the logic here:
* We periodically send notifications about reviews/rejections. 
* What happens after the notification is sent will be included in the next scheduled notification.

In particular, point 3 would become an incentive to not read notifications (if I read them frequently, I end up getting more notifications).

If we're concerned about the lag between two notifications, we can set them as daily (every 24h), and re-evaluate based on how many we send.

**Comment by flodolo** [comment]
One more thought: we should add links to the message. The problem is that we don't know which strings were actually accepted or rejected, unless we store the IDs as part of the notification, and use them as filters somehow?

Worst case scenario, we can at least link to approved/rejected strings with the user as author.

**Comment by eemeli** [comment]
> In particular, point 3 would become an incentive to not read notifications (if I read them frequently, I end up getting more notifications).

With the proposed system, new notifications would be generated at most once per day, which seems to be what you're proposing as an alternative?

> One more thought: we should add links to the message. The problem is that we don't know which strings were actually accepted or rejected, unless we store the IDs as part of the notification, and use them as filters somehow?

One reason for triggering the notification creation/update from the accept/reject action is that this provides the string in question directly, and allows for linking at least one of the strings directly. Otherwise, we either need to add a new capability of explicitly listing strings by id, or list all approved/rejected strings authored by the user.

**Comment by flodolo** [comment]
> With the proposed system, new notifications would be generated at most once per day, which seems to be what you're proposing as an alternative?

I missed that. In that case, that concern is not valid.

I still feel weird about notifications that change after being sent (and while waiting to be read). I also wonder if that's potentially going to create some confusion for users of the add-on (lag between Pontoon knowing these notifications are read, and user reading them in the add-on).

Just to be clear, in point 2 you're suggesting to update a notification already sent, but not read by the user? 

> One reason for triggering the notification creation/update from the accept/reject action is that this provides the string in question directly, and allows for linking at least one of the strings directly.

How would that work in practice? You'd store the link to a specific string as part of the notification?

**Comment by eemeli** [comment]
> I still feel weird about notifications that change after being sent (and while waiting to be read). I also wonder if that's potentially going to create some confusion for users of the add-on (lag between Pontoon knowing these notifications are read, and user reading them in the add-on).

The starting point here is to consider unread notifications as well, unread. Therefore, any changes made to them are not visible to the user until they actually read the notification. The intent is to reduce the number of notifications, so that if e.g. some strings are accepted today, some tomorrow, and you only look at your notifications on the day after that, we only show you one rather than two.

There should not be any significant difference between notifications shown on the site, and in the add-on. Both use the same API calls to get new notifications and to mark them read.

> Just to be clear, in point 2 you're suggesting to update a notification already sent, but not read by the user?

No, there I'm suggesting what to do after the following sequence of events:
1. A translation is accepted
2. A notification is created
3. User reads the notification within 24 hours
4. Another translation is accepted, still within 24 hours of step 1.

The original proposal is that in this situation the first notification is effectively replaced by a new one, which refers to two accepted strings.

One alternative here would be not to show the notification to the user until at least 24 hours have passed from its creation, which would avoid this situation.

> > One reason for triggering the notification creation/update from the accept/reject action is that this provides the string in question directly, and allows for linking at least one of the strings directly.
> 
> How would that work in practice? You'd store the link to a specific string as part of the notification?

Pretty much, yes. And then if a second accepted/rejected translation is added to the notification, switch to a filter link that lists the user's most recent accepted or rejected translations.

**Comment by mathjazz** [comment]
> One alternative here would be not to show the notification to the user until at least 24 hours have passed from its creation, which would avoid this situation.

Which is effectively a cron job then?

What if we stick to the "cron job" approach for now, explore the ability to "update notifications" later (including for the use case from #2093), and if time permits implement a new filter to show reviewed suggestions within a given period of time, which we'll also new in the [new profile page](https://discourse.mozilla.org/t/request-for-feedback-improving-pontoon-profile-page-deadline-march-14/93743)?

**Comment by flodolo** [comment]
> There should not be any significant difference between notifications shown on the site, and in the add-on. Both use the same API calls to get new notifications and to mark them read.

Not in my experience. The add-on shows you the notification, but it doesn't mark them as read automatically. You need to manually mark them all as read.

As Matjaz suggested, I would start with a basic approach (cron-job). 

I appreciate the idea of reducing the number of notifications we send, but it feels like we'd be adding quite a bit of complexity for a few cases. Also, the amount of notifications sent by this feature would be a tiny fraction of what we send for project updates, and we probably need to address the over-notification problem as a whole.

**Comment by eemeli** [comment]
> > One alternative here would be not to show the notification to the user until at least 24 hours have passed from its creation, which would avoid this situation.
> 
> Which is effectively a cron job then?

Except that it wouldn't need a cron job to maintain the proper state, as the notifications exist at all times but are filtered for the first 24 hours.

> What if we stick to the "cron job" approach for now, explore the ability to "update notifications" later (including for the use case from #2093), and if time permits implement a new filter to show reviewed suggestions within a given period of time, which we'll also new in the [new profile page](https://discourse.mozilla.org/t/request-for-feedback-improving-pontoon-profile-page-deadline-march-14/93743)?

Sure.

> > There should not be any significant difference between notifications shown on the site, and in the add-on. Both use the same API calls to get new notifications and to mark them read.
> 
> Not in my experience. The add-on shows you the notification, but it doesn't mark them as read automatically. You need to manually mark them all as read.

Okay, then it might be possible for a user to see (but not "read") a notification in the add-on, and to later observe the contents of that same notification to be different. As this change would only ever be incremental (e.g. "3 accepted" -> "4 accepted"), I don't think that this would be a significant source of confusion, esp. as the notifications in the add-on and on the site would match at any point in time, excluding any differences in refresh rates.
