### ISSUE TITLE
Optimize generation of data for tags

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2264]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1691956](https://bugzilla.mozilla.org/show_bug.cgi?id=1691956)
Bug Reporter: @flodolo
Blocker for:  [Bug 1701175](https://bugzilla.mozilla.org/show_bug.cgi?id=1701175)

Currently, opening the tags panel for a project as large as Firefox might take 20-30s, and sometimes it results in a blank page.

We should cache or store this data, instead of generating it on the fly when the page is requested.

**Comment by mathjazz** [comment]
Tags calculate stats and the latest activity data on the fly rather than have it stored denormalized like Project, Locale, and ProjectLocale dashboards. 

Denormalizing this data for Tags is non-trivial because the Tags codebase is unmaintained and uses code patterns that are not used elsewhere in the code. It also has other problems than just performance - the tag selector widget uses its own frontend stack and it’s own design language.

The action item here is to implement replacement for Tags targeting excellent Apdex score, and drop the existing pontoon.tags module eventually. We should also consider replacing Tags with something simpler like Resource priority.
