### ISSUE TITLE
Daily sync errors for android-l10n project

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2306]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1726957](https://bugzilla.mozilla.org/show_bug.cgi?id=1726957)
Bug Reporter: @flodolo
CC:   @mathjazz

Starting August 18, we constantly get Sync errors from android-l10n

```
! [rejected]            HEAD -> master (fetch first)
error: failed to push some refs to 'git@github.com:mozilla-l10n/android-l10n.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```

My guess is that Pontoon doesn't know how to deal gracefully with two projects working on the same repository, given only Pontoon writes to it these days.

**Comment by mathjazz** [comment]
Not really a P2 bug.

**Comment by mathjazz** [comment]
Currently we mitigate this issue by excluding all messages containing "android" from the "Failed to Sync locale" alert in Papertrail. The query looks like this:
`"Failed to sync locale" AND -"new remote head" AND -"android"`

That's obviously suboptimal, because we might miss valid errors that happen in our Android projects. And we (or other users) might bump into the same issue in non-android projects.

Let's change the [log message for Git repositories](https://github.com/mozilla/pontoon/issues/2306#issuecomment-918459383) to:

Aug 21 15:18:12 mozilla-pontoon app/worker.1 Failed to sync locale hu for project focus-for-android due to commit error: **Remote contains work that you do not have locally.**
```

**Comment by flodolo** [comment]
How would this approach help solving the issue? We're still going to have a ton of issues, the difference is that we can filter out the new message instead of filtering out `android` completely.

But to me this issue is not about filtering less, is about reducing the error in the first place (e.g. try to pull before committing, or `git pull --rebase` before pushing).

**Comment by mathjazz** [comment]
We can't do much about the underlying issue, so we're making the logging consistent among different VCS systems in order to be able to handle alerts more reliably. We currently solve the daily alert issue originally reported here by hard-coding the project name in the [filter query](https://github.com/mozilla/pontoon/issues/2306#issuecomment-1554420811).

We already pull before pushing. But by the time we (try to) push, the remote repository changes and push fails. If we'd pull again, just before trying to push, we'd risk conflicts and skip potentially relevant changes.

One thing we could do is trigger the next sync for the project immediately after the push fails, without waiting for the next job. But that's a lot of complexity for such a low-impact bug (we only had 5 errors of this type in the past 10 days).

**Comment by mathjazz** [comment]
Change the filter: replace "android" with "Remote contains work that you do not have locally".

**Comment by flodolo** [comment]
> Change the filter: replace "android" with "Remote contains work that you do not have locally".

OK, that makes sense then 👍🏼
