### ISSUE TITLE
Perform a community survey to pick features to implement in H1 2022

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2355]
We need to select ~10 features and let the community vote on them.

**Comment by mathjazz** [comment]
A batch of candidate features collected from 2021 Workshop Notes, 2021 OKR Planning notes and other filed feature requests.

- https://github.com/mozilla/pontoon/issues/2062
- https://github.com/mozilla/pontoon/issues/2094
- https://github.com/mozilla/pontoon/issues/2108
- https://github.com/mozilla/pontoon/issues/2135
- https://github.com/mozilla/pontoon/issues/2138
- https://github.com/mozilla/pontoon/issues/2141
- https://github.com/mozilla/pontoon/issues/2157
- https://github.com/mozilla/pontoon/issues/2203
- https://github.com/mozilla/pontoon/issues/2139
- https://github.com/mozilla/pontoon/issues/2177
- https://github.com/mozilla/pontoon/issues/2183
- https://github.com/mozilla/pontoon/issues/2305
- https://github.com/mozilla/pontoon/issues/2309
- https://github.com/mozilla/pontoon/issues/2059
- https://github.com/mozilla/pontoon/issues/2060
- https://github.com/mozilla/pontoon/issues/2310
- https://github.com/mozilla/pontoon/issues/2037
- https://github.com/mozilla/pontoon/issues/2082
- https://github.com/mozilla/pontoon/issues/2036
- https://github.com/mozilla/pontoon/issues/2255
- https://github.com/mozilla/pontoon/issues/2050
- https://github.com/mozilla/pontoon/issues/2276
- https://github.com/mozilla/pontoon/issues/2270
- https://github.com/mozilla/pontoon/issues/2167
- https://github.com/mozilla/pontoon/issues/2152

**Comment by Delphine** [comment]
* [notifications] Notify suggestion authors when their suggestions get accepted/rejected #2094
* [notifications] Allow to read notifications one by one, or mark notifications as unread #2108
* Users should have a way to contact existing locale managers #2157
* Provide new contributors with guidelines before adding their first suggestion in a locale #2305
* Add a badge to new users' avatars #2309
* [terminology] Enable localizers to propose new terms #2310
* [translate] Add a "reject all" batch action #2082
* Simplify translation process for similar locales #2255
* [translate] Show indication for good results from Translation Memory #2050
* Link project names in Concordance search results to translate view #2276
* Redirect old project slugs to the new one #2152

**Comment by flodolo** [comment]
This is my list:

* [[notifications] Notify suggestion authors when their suggestions get accepted/rejected #2094](https://github.com/mozilla/pontoon/issues/2094)
* [[notifications] Allow to read notifications one by one, or mark notifications as unread #2108](https://github.com/mozilla/pontoon/issues/2108)
* [Users should have a way to contact existing locale managers #2157](https://github.com/mozilla/pontoon/issues/2157)
* [Provide new contributors with guidelines before adding their first suggestion in a locale #2305](https://github.com/mozilla/pontoon/issues/2305)
* [Add a badge to new users' avatars #2309](https://github.com/mozilla/pontoon/issues/2309)
* [Create a light theme and enable switching to it #2141](https://github.com/mozilla/pontoon/issues/2141)
* [[translate] File priority and tags not visible in translate view #2139](https://github.com/mozilla/pontoon/issues/2139)
* [Pontoon special character shortcuts #2059](https://github.com/mozilla/pontoon/issues/2059)
* [Link project names in Concordance search results to translate view #2276](https://github.com/mozilla/pontoon/issues/2276)* 
* [Add Timeline tab to Project, Locale, ProjectLocale dashboards #2138](https://github.com/mozilla/pontoon/issues/2138)

Additional notes:

* [Tracking changes in the translation text field #2062](https://github.com/mozilla/pontoon/issues/2062)

This doesn't seem clearly defined, as pike pointed out it might be a good idea to split into two (at least). I'm not sure how you could present it to users in a survey, in a short sentence (this is a problem for others as well).

* [[translate] Show indication for good results from Translation Memory #2050](https://github.com/mozilla/pontoon/issues/2050)

Is it just me or this has been pretty much fixed by 3-columns, with the machinery tab always visible (with the match indication)?

Some of these features are hardly user-facing. As a PM, I would like to see #2152 (project slugs) fixed, but which type of user would vote for that?

I'm not completely sure we should have #2138 (timeline in dashboards), because that looks like a behemoth compared to all others, on top of being very open-ended.

**Comment by mathjazz** [comment]
>     * [Tracking changes in the translation text field #2062](https://github.com/mozilla/pontoon/issues/2062)
> 
> This doesn't seem clearly defined, as pike pointed out it might be a good idea to split into two (at least). I'm not sure how you could present it to users in a survey, in a short sentence (this is a problem for others as well).

True. I've split it into #2356 and #2357.

>     * [[translate] Show indication for good results from Translation Memory #2050](https://github.com/mozilla/pontoon/issues/2050)
> 
> 
> Is it just me or this has been pretty much fixed by 3-columns, with the machinery tab always visible (with the match indication)?

I think making Machinery always visible was a step in the right direction, but I think we can do more when it's highly likely that one of the results in Machinery is accurate. For example, I'd like to experiment with putting it into the editor directly (with a clear indication that it's a Machinery suggestion).

> Some of these features are hardly user-facing. As a PM, I would like to see #2152 (project slugs) fixed, but which type of user would vote for that?

Agreed.

> I'm not completely sure we should have #2138 (timelines), because that looks like a behemoth compared to all others, on top of being very open-ended.

I don't think it's too big. In essence, a timeline is "just" a presentation of data from the ActionLog and Notification models, filtered by project, locale or both.

**Comment by mathjazz** [comment]
I've excluded two additional ideas:

1. The following was voted 5th out of 6 ideas in the Notification survey earlier this year, so its chances of being picked are pretty slim:
#2108

2. The following requires agreement on how we want to manage Terminology going forward (i.e. somebody would need to triage proposed terms), so I worry we might promise something we won't be able to deliver (and I'd rather revisit this important topic at the next OKR planning):
#2310

That leaves us with 5 features you've both picked:
* #2094
* #2157
* #2305
* #2309
* #2276

4 additional features at least one of you have picked:
* #2050
* #2255
* #2141
* #2059

1 additional features for which bugs (dupes) have been filed several times:
* #2060

**Comment by mathjazz** [comment]
The survey has been released via blog, twitter, and direct emails.
