### ISSUE TITLE
Ability to hide email address

### ISSUE THREAD

**Issue by pedroldk** [mozilla/pontoon#2407]
Would it be possible to hide the email address from the profile? I believe it is a breach of security that any logged-in user can check the email address of any other user. If this is the case of being able to contact that user, then there are other ways to do it. (GitHub profile, Twitter account, direct message, etc.)

**Comment by mathjazz** [comment]
Hey @pedroldk, thanks for filing the issue!

[Pontoon Terms of Use](https://pontoon.mozilla.org/terms/) and [Mozilla Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/) both state: "Your name and email address, or a derivative of it, may be attached to your contributions and so be visible worldwide."

In practice, that means Pontoon (which is designed to work with VCS systems as translation storage) sets the commit author to user's email address when translation are sent to VCS ([example](https://github.com/mozilla-l10n/android-l10n/commit/d3632b5950c47798760389998eeb1e760d72845c)). We also use email addresses to represent users in Pontoon UI (e.g. for translation attributions) in case they don't set a display name, because that's the only identifier we have.

I don't see a lot of room for change in any of these use cases. We could however hide the email address from the user's profile if the user explicitly requests it. Although in this case we risk the ability for a Locale manager for example to reach out to the user in case they want to mentor them etc.

**Comment by pedroldk** [comment]
Hi @mathjazz, thank you for taking the time to answer. I do understand the advantages, and it's not like nowadays there are more ways to secure your email address. Closing the issue ;)

**Comment by mathjazz** [comment]
I think this is still a valid issue. :)

In the profile page, we could hide the email address, unless the user accessing the page is an Admin or Locale Manager (who might want to get in touch with the user). Also, hiding an email address should be optional, because some users (especially admins and managers) might want others to be able to get in touch with them easily.

We could also point out that hiding an email address does not apply to VCS and link to the Terms page with explanation.

**Comment by pedroldk** [comment]
@mathjazz seems like a great solution, it preserves the hability for admins to contact directly and gives more privacy to users ;)

**Comment by avm99963** [comment]
GitHub allows users to hide their email address when committing by using an address of the form `ID+username@users.noreply.github.com`. I don't know how difficult it would be to implement this but I think it would be a good solution for hiding the actual email address in commits.

**Comment by LilianaMoore** [comment]
Bots are harvesting email addresses from contributors subpage. You don't have to be logged in.  https://pontoon.mozilla.org/ru/mozillaorg/contributors/ This is a serious privacy/security flaw.

**Comment by flodolo** [comment]
> Bots are harvesting email addresses from contributors subpage. You don't have to be logged in. https://pontoon.mozilla.org/ru/mozillaorg/contributors/ This is a serious privacy/security flaw.

This is unrelated, and possibly a different issue. Users have the possibility to pick a username that has nothing to do with their email, and that will show up in that page.

In the profile page, the email address is hidden if you're not logged in, e.g.
https://pontoon.mozilla.org/contributors/Ia-ei3AiMfLnsvApB2cstaDhRuQ/

**Comment by mathjazz** [comment]
Users now have the ability in settings to make their email address on their profile page on visible to either Translators or Logged in users. This ability effectively makes this bug resolved. Email addresses of team and project managers are visible to all logged in users.

**Comment by irishgeoff22** [comment]
you could use this tool to[hide email address](https://veilmail.io)
