### ISSUE TITLE
Implement contribution graph

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2487]
Reference: [specs](https://github.com/mozilla/pontoon/blob/master/specs/0111-redesign-profile-page.md)

This issue tracks the implementation of the contribution graph.

Blocked by:
* #2485
* #2486

**Comment by mathjazz** [comment]
We should consider #2138 when implementing the bottom part of the widget that displays detailed data of the selected time range.

**Comment by mathjazz** [comment]
Adding a link to the old and now obsolete proposal for the [review dashboard](https://docs.google.com/document/d/18fuv9B33LLrL0U2MUbZpGGmlZj4-QR-fX4fDIHSrtTM/edit#heading=h.jgclo7dnn5bo). It has some nice ideas (like diff) and I like that it also includes comments.

If we want the "Reviews received" view to serve as the review report, it must also include comments. I thought it's worth mentioning here since we didn't mention it in the spec.
