### ISSUE TITLE
"Same translation already exists"

### ISSUE THREAD

**Issue by buhtz** [mozilla/pontoon#2665]
I'm new to pontoon and looking for an easy-to-use translation plattform that I can integreat in Codeberg.org (Gitea based) and GitHub.

I was playing arround with pontoon and have to say on the first sight it seems extrem complex and I'm scared that it will drive some potential contributors away from my projects.

e.g. when I try to translate a givin string I always got the message "Same translation already exists". It is not clear for my why. And when there is a translation why does pontoon offers it to me? This is waste of time and ressources.

**Comment by mathjazz** [comment]
Hi @buhtz. If it seems extremely complex even on the first sight, I don't think it's a good idea to use it. :) One other important thing to note: at least for the time being, our support for 3rd party deployments is sadly close to non-existent.

**Comment by mathjazz** [comment]
As for the "Same translation already exists" error, please file a separate issue with steps to reproduce. Thanks!

**Comment by buhtz** [comment]
> our support for 3rd party deployments is sadly close to non-existent.

Maybe I misunderstand the background of the project. Aren't you Mozilla? Do you separate between FOSS users/developers and paying customers?

I tough pontoon is a FOSS project.

**Comment by mathjazz** [comment]
Pontoon is developed by Mozilla and used by the awesome Mozilla l10n community to localize Mozilla software at https://pontoon.mozilla.org/.

Due to its [license](https://github.com/mozilla/pontoon/blob/master/LICENSE), several other projects use their own instance of Pontoon to localize their software. Mozilla however does not offer any support for non-Mozilla deployments.

If you have more questions about custom deployments, please use [Discourse](https://discourse.mozilla.org/c/pontoon/258) or [Matrix](https://chat.mozilla.org/#/room/#pontoon:mozilla.org).
