### ISSUE TITLE
Use contact email for commits if it exists

### ISSUE THREAD

**Issue by ImUrX** [mozilla/pontoon#2740]

**Comment by mathjazz** [comment]
Thanks for the idea. I think it makes sense. 

@flodolo Since you were the author of the contact email address, do you have any reservations against this?

**Comment by flodolo** [comment]
I'm personally against this idea.

The goal of the contact email address is to allow people to specify their preferred way to be contacted. The assumption (hope) is that they'll specify an address where emails won't be buried under a ton of other messages and automated notifications. Most users don't care or know about VCS, as Pontoon make its existence transparent.

By using it in commit messages, we'll be disclosing those email addresses, and expose them to spam. Also, the contact email address is by default visible only to translator, optionally to logged in users. It's never supposed to be visible outside of Pontoon.

If we want to do this, it should be either a flag in the profile ("Use my contact email address when committing to VCS"), or a different field ("Email address to use in commit messages to VCS"). And maybe we need a flag to anonymize the commits (I have a feeling it was asked at some point), since I don't think most people realize their login email address ends up in VCS logs.

**Comment by mathjazz** [comment]
All good points. Let's close the issue and open a new one if needed to use a different email address for commit messages.

[Pontoon Terms of Use](https://pontoon.mozilla.org/terms/) and [Mozilla Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/) both state "Your name and email address, or a derivative of it, may be attached to your contributions and so be visible worldwide.", so I'd avoid anonymizing commits.

Note that there's also #2121, which tracks the ability to change the login email address.
