### ISSUE TITLE
When hovering an approved string, the tooltip should also say when the strings was approved, not just by whom

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2763]
Currently, it also says "Approved by X". To understand when it was reviewed, I need to look at VCS.

**Comment by mathjazz** [comment]
See also #2660.

**Comment by mathjazz** [comment]
We're showing the translation creation time in the tooltip (rather than the review time).

While on it, we should also make the format in the translation creation time tooltip match the format used here (specifically, we should drop the weekday).

<img width="419" alt="Screenshot 2024-07-02 at 14 09 17" src="https://github.com/mozilla/pontoon/assets/626716/35c27bc9-f288-448e-b143-5876a779739d">
