### ISSUE TITLE
Fluent Plurals UI broken for untranslated strings in some locales

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2780]
https://pontoon.mozilla.org/tg/firefox/browser/browser/aboutLogins.ftl/?string=275911

First, when you open the string, the input field is empty and there's no variants UI.

If you copy the English string, then things get even weirder: you type in the "other" line, and the text ends up in "one" (but only one character).

**Comment by mathjazz** [comment]
Some early findings...

Same set of problems can be reproduced for `id` or `th`: 
https://pontoon.mozilla.org/id/firefox/all-resources/?string=275911
https://pontoon.mozilla.org/th/firefox/all-resources/?string=275911

But not for `nb-NO` or `or`:
https://pontoon.mozilla.org/nb-NO/firefox/all-resources/?string=275911
https://pontoon.mozilla.org/or/firefox/all-resources/?string=275911

Special case is Spanish, which shows an unexpected plural form - `many` - without an example:
https://pontoon.mozilla.org/es-ES/firefox/all-resources/?string=275911

**Comment by flodolo** [comment]
French has the same behavior as Spanish, but it doesn't do the weird typing bug.

So, it looks like we're picking the wrong number of plural forms, and break the UI when there's only one?

**Comment by mathjazz** [comment]
Right, for `id` and `th` 1 field is actually expected. But not for `tg`.

**Comment by eemeli** [comment]
One part of the disparity is coming from relying on `Intl.PluralRules`. In today's Firefox Nightly 112.0a1:

```js
new Intl.PluralRules('tg').resolvedOptions().pluralCategories 
// [ "other" ]

new Intl.PluralRules('es').resolvedOptions().pluralCategories
// [ "many", "one", "other" ]
```
This effectively matches the behaviour at runtime, which also relies on `Intl.PluralRules`.

As at least Chrome appears to not only rely on CLDR data, a `tg` plural string will work as expected there: https://pontoon.mozilla.org/tg/firefox/all-resources/?string=275911

The `many` in Spanish and all other Romance languages is a valid [CLDR category](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#es) for millions; previously only available in French. It doesn't contain an example because our [iteration](https://github.com/mozilla/pontoon/blob/master/translate/src/hooks/usePluralExamples.ts) stops at 1000.

The editor bug is a real bug that needs to be fixed ASAP, and separate from all of the above.

**Comment by flodolo** [comment]
> One part of the disparity is coming from relying on `Intl.PluralRules`.

Why are we doing this? We store that information as part of the locale in Pontoon for a reason 🤔

**Comment by mathjazz** [comment]
Let's use this issue to switch back to using the plural forms as defined in the database. This is the most urgent matter.

I'm not aware of examples beyond 1000 apart from the ones the patch for this bug will remove. Ideally, the solution should be to fix #2042 - calculate examples on Locale creation and store them in DB.

I'm not sure how to file the "editor bug" (assuming that's typing to "other", adding to "one"). Is that reproducible outside the scope of this bug?

**Comment by eemeli** [comment]
> > One part of the disparity is coming from relying on `Intl.PluralRules`.
> 
> Why are we doing this? We store that information as part of the locale in Pontoon for a reason 🤔

Because this is how we're formatting the messages. As is, the Tajik `one` variants will never be selected for Fluent messages in Firefox because `new Intl.PluralRules('tg').select(x)` will always return `'other'` for any `x`.

The right place to fix this is in the data that's driving `Intl.PluralRules`, so ultimately CLDR.

We need to store the information in Pontoon for plurals in other formats, i.e. Gettext and PluralRule.

**Comment by mathjazz** [comment]
We shouldn't show different plurals forms in different browsers, though.

We also shouldn't have different plurals forms in different strings of the same project (already translated vs. new).

And I'm looking forward to using `Locale.cldr_plurals` for pretranslation, so in python.

Is there a better option going forward than to revert and migrate back to `Intl.PluralRules` once things in CLDR and browsers work as expected?

**Comment by flodolo** [comment]
> As at least Chrome appears to not only rely on CLDR data, a `tg` plural string will work as expected there: https://pontoon.mozilla.org/tg/firefox/all-resources/?string=275911

BTW, if I visit that string with Chrome (110), I get 3 fields (one, many, other), which doesn't match either Pontoon or Nightly?

**Comment by flodolo** [comment]
One more note (sorry for the email spam): this change is going to result in a cascade of warnings on my side, given compare-locales uses its own list of plurals, which matches what Pontoon had (not CLDR).
