### ISSUE TITLE
Machinery: Inconsistent search output between front page and translation view

### ISSUE THREAD

**Issue by bcolsson** [mozilla/pontoon#2836]
When searching for a string or keyword in machinery, the machinery available from the front page (https://pontoon.mozilla.org/machinery/) and from the translation view differ, with the one in the translation view offering more results. See example below:

Top page:
![Screenshot 2023-05-05 at 11 18 11](https://user-images.githubusercontent.com/38174554/236537150-9e4a779b-1b32-47cc-a466-9fea9b363052.png)

Translation view:
![Screenshot 2023-05-05 at 11 00 53](https://user-images.githubusercontent.com/38174554/236536996-52bb96a9-10d5-42dc-84c0-60b9716e3602.png)

**Comment by mathjazz** [comment]
That's by design, actually. 

But I see why it's confusing... The tab title on the translate page says Machinery, but the feature you're using here is Concordance search - the name that is only visible in the input box placeholder. 

These are two separate things - the actual Machinery in the translate page takes the source string as the input and should work the same as the Machinery page.

[Concordance search](https://blog.mozilla.org/l10n/2021/03/09/concordance-search-lands-in-pontoon/) works a little differently. Ideally, it should be in a separate tab, but we have space constraints. We could for example show the tab title only on the active tab, and use icons on inactive ones.

**Comment by bcolsson** [comment]
@mathjazz: Okay, I'll add a snippet about this distinction in the documentation.
