### ISSUE TITLE
GetText check fails incorrectly on newline

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2991]
https://pontoon.mozilla.org/en-GB/all-projects/all-resources/?string=286055

If you copy the source string, an extra line is added at the back, and that fails the checks for GetText.

**Comment by mathjazz** [comment]
COPY works as expected: source strings ends with a newline and it gets copied to the translation area.

What is surprising is that the newline check fails:
https://github.com/mozilla/pontoon/blob/main/pontoon/checks/libraries/pontoon_db.py#L73

I was able to submit the translation without a problem yesterday, but not today:
https://pontoon.mozilla.org/sl/all-projects/all-resources/?string=286055

@eemeli, could it be that #2926 fixes it? I don't see anything pointing that way there.

**Comment by IanN-GH** [comment]
Another example https://pontoon.mozilla.org/en-GB/all-projects/all-resources/?string=286198

**Comment by bcolsson** [comment]
I encountered an additional complication today in dealing with this error - when trying to adjust whitespace to a suggestion to correct this error I wasn't able to save/approve a translation. The editor wasn't considering changes to the whitespace as changes to the string, so it'd keep trying to approve the string that was triggering the newline error. For example [this string](https://pontoon.mozilla.org/da/firefox-accounts/LC_MESSAGES/client.po/?string=286060):  I had to add a space after the "du:" and before the <br /> to make the translation "different" and allowed me to save it. Otherwise it'd still consider this the same as the previous suggestion and only allow me to "approve". (Which would fail the newline check.)

**Comment by eemeli** [comment]
This looks like a back-end bug. Testing with [this string](https://mozilla-pontoon-staging.herokuapp.com/fi/all-projects/all-resources/?string=192448) (the only non-obsolete gettext string with a trailing newline I could find), copy+suggest POSTs to `/translations/create/` with a `translation` value that exactly matches the source, including the trailing newline, but receives a `pErrors: [ "Ending newline mismatch" ]`.
