### ISSUE TITLE
Unify admin user status definition

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3418]
Admin user status introduced in https://github.com/mozilla/pontoon/pull/3400 is defined in two different ways: 

1. As a [superuser](https://github.com/mozilla/pontoon/commit/3910a994f7a07ea3d530a49879355909841d80e8#diff-3e822354a9d9b515f80ad2940a7fb3685084a1ec090224d30fc5ede87f4b0174R200-R201) (user with all permissions).

2. As a [user with access to Pontoon admin](https://github.com/mozilla/pontoon/blob/3910a994f7a07ea3d530a49879355909841d80e8/pontoon/base/views.py#L876) (these users can also be selected from the list of Project Managers).

We should unify that and only use one definition. Which one?

I think the latter, because these users add comments and fix translations, so their avatars will actually appear in the History and Comments panels.

They will also be listed as Project Managers in the Project dashboards. So we should also change the status name from Admin to PM.

**Comment by flodolo** [comment]
(cc @bcolsson for visibility)

This is collapsing at least two different issues, and I believe the starting point is incorrect (users with access to Pontoon admin don't currently show up as potential project managers when setting up a project).

I don't think admins and project managers should be collapsed:
- A project manager might just be a point of contact for the project who doesn't have rights to make changes to translations (they're not experts in localization). They're only available to answer questions, or relay them to developers and bring back the answer.
- The PM is a specific figure with knowledge on that project, e.g. Peiying shouldn't show up as a PM for Firefox.
- An admin might just be a developer who's not going to make any changes to translations (e.g. Harmit). At that point they're unlikely to show up in the Translate UI, but what would be the point of marking them as PMs if they do? 

As for the definition of Admin, I would probably use "users with access to admin", since that's a subset of superuser.

Final consideration: I have working code to add the PM label [here](https://github.com/mozilla/pontoon/compare/main...flodolo:pontoon:test_pm). While I don't fully understand the front-end code, the priority of users when it comes to the banner seems to be inconsistent between front-end and back-end, even more so after #3414:
* Priority should go to roles within the locale (I'm a manager for Italian first in the context of Italian localization, because that's an indication for users contributing there).
* Then comes the PM role. It's less important to know that Bryan is an admin when he leaves a comment in Firefox, he's important to highlight that he's the point of reference for that project (i.e. a PM).
* Finally comes the Admin role.

**Comment by mathjazz** [comment]
> While I don't fully understand the front-end code, the priority of users when it comes to the banner seems to be inconsistent between front-end and back-end, even more so after #3414:

Good point! Filed https://github.com/mozilla/pontoon/pull/3421 for an immediate fix.
