### ISSUE TITLE
Pontoon overwrites changes made in VCS

### ISSUE THREAD

**Issue by Osmose** [mozilla/pontoon#35]
# Problem
Pontoon doesn't currently do any conflict resolution; if someone commits strings directly to version control, Pontoon will overwrite them. This also crops up when two instances of Pontoon are pointing to the same repo (such as the staging and production Heroku instances, which used to both point at mozilla/pontoon-intro). Both instances get in a commit war as each overwrites the other.

# Why?
Pontoon stores the entire state of a project's strings in its database. When Pontoon commits its strings to VCS, it exports the database into language files and then commits them (if there are no changes, the commit for that locale fails or shows no changes).

When someone commits directly to version control, those changes don't hit the database before Pontoon commits its language files, meaning that Pontoon will overwrite the changes made.

# Possible Solutions

## Store Changes
Instead of exporting the database into language files, whenever someone makes a change that would affect the language files (approving or deleting strings), store that as a `Modification`. When running the automated commit job, start by downloading the latest version of the language files and reading them. Then go through each `Modification` and make the change to the required language file. Once done, save the language file back out and commit them.

This way, external edits are preserved, but a string is both changed externally and changed by Pontoon, Pontoon's change takes precedence. Conflicts in VCS are avoided as we start off by downloading the latest revision, and if we still hit a conflict we can just try again after a short delay (and eventually fail and email an admin if we continually fail to commit).

A possible simplistic `Modification` implementation may look something like:

```python
class Modification(models.Model):
    DELETE = 0
    APPROVE = 1

    user = models.ForeignKey(User)
    entity = models.ForeignKey(Entity)
    translation = models.ForeignKey(Translation)
    action = models.IntegerField(choices=[(DELETE, 'DELETE'), (APPROVE, 'APPROVE')])

    def perform(self):
        if self.action == self.DELETE:
            # Delete translation
        else if self.action == self.APPROVE:
            # Approve translation
```

**Comment by mathjazz** [comment]
Pontoon actually does some sort of conflict resolution, but it's VCS-conditional and thus implicit.

Take SVN as an example. If someone commits strings directly to VCS, Pontoon will not be able to commit its changes, because file(s) will be out of date. After update_projects is executed, it will be able to commit in the next cycle. If changes were made to same strings in both, the repo and Pontoon, the repo will win.

That is however not the case with Git. And while we didn't use Git-based l10n repos in the past too much, today we use it more and more often. We're actually moving all l10n SVN-based repos to GitHub. So the problem this issue raises should be of high priority.

I like the proposed solution. It's basically update/pull first and then commit/push, with Pontoon having precedence over repository. And storing Modifications should help significantly with reducing the commit_projects execution time (https://github.com/mozilla/pontoon/wiki/Roadmap#optimize-commit_projectspy).

We also need to be careful what happens with fuzzy string in PO files. If string is fuzzy in the repo and gets "unfuzzied" in Pontoon, it should also become unfuzzied after commit. Seems like this should work with the approach you are proposing, since unfuzziing in Pontoon is performed by approving translation.

**Comment by Osmose** [comment]
Filed in Bugzilla as https://bugzilla.mozilla.org/show_bug.cgi?id=1178874
